In [26]:
import pandas as pd

In [28]:
import matplotlib.pyplot as plt

In [30]:
hauler = pd.read_csv('../data/trash_hauler_report.csv')

In [32]:
hauler

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1.727970e+06,686779.478089
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1.781137e+06,632448.551144
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1.749711e+06,669201.601569
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1.781360e+06,637742.006846

In [34]:
hauler.rename(columns={'Request ': 'Complaint'}, inplace=True)

In [36]:
hauler = hauler.dropna(subset=['Complaint', 'Description'])

dropna function removes null/missing values.
subset=['Incident Address'] tells Pandas to check only the Incident Address column.

In [39]:
hauler['Complaint'] = hauler['Complaint'].astype(str)

C:\Users\user\AppData\Local\Temp\ipykernel_17100\2552666913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hauler['Complaint'] = hauler['Complaint'].astype(str)

In [41]:
hauler['Description'] = hauler['Description'].astype(str)

C:\Users\user\AppData\Local\Temp\ipykernel_17100\1517836189.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hauler['Description'] = hauler['Description'].astype(str)

In [43]:
missed_pickups = hauler.loc[
    hauler['Complaint'].str.contains('miss', case=False, na=False) |
    hauler['Description'].str.contains('miss', case=False, na=False)
]

The str.contains function checks to see if 'miss' exists anywhere within Complaint and Description. The false parameter makes capitalization case not important or null.

In [47]:
missed_pickups = missed_pickups.dropna(subset=['Trash Hauler'])

In [49]:
missed_pickups

,Request Number,Date Opened,Complaint,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066
7,25327,11/01/17,Trash Collection Complaint,"Trash out on time, miss again Tuesday. ALLEY",1816 Jo Johnston Ave,37203.0,METRO,9208,21.0,1.731459e+06,666013.601229
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1.781137e+06,632448.551144
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1.749711e+06,669201.601569
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1.781360e+06,637742.006846

In [51]:
trash_hauler = missed_pickups.loc[
    missed_pickups['Trash Hauler'].str.contains("RED RIVER", case=False, na=False)
]

In [53]:
trash_hauler

,Request Number,Date Opened,Complaint,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066
8,25330,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1.794534e+06,618749.342732
10,25341,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed trash pickup - resident has at curb for...,3113 HYDES FERRY RD,37218.0,RED RIVER,4204,2.0,1.721578e+06,676018.399900
...,...,...,...,...,...,...,...,...,...,...,...
20220,267121,11/01/19,Trash - Curbside/Alley Missed Pickup,missed,"2709 Crestdale Dr, Nashville, TN 37214, United...",37214.0,RED RIVER,1502,15.0,1.770240e+06,676334.399319
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1.781137e+06,632448.551144
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1.781360e+06,637742.006846

In [67]:
test = trash_hauler['Incident Address'].value_counts().to_frame().reset_index()

In [75]:
test

                                       Incident Address  count
0     12546 old hickory blvd, nashville, tn 37013, u...     19
1                              5135 hickory hollow pkwy     18
2                                     3710 n natchez ct     18
3     6007 obrien ave, nashville, tn 37209, united s...     18
4     802 crescent rd, nashville, tn 37205, united s...     17
...                                                 ...    ...
9032  181 thompson ln, nashville, tn 37211, united s...      1
9033                                  1604 ardenwood ct      1
9034  255 haverford ave, nashville, tn 37205, united...      1
9035                                  6604 fleetwood dr      1
9036  604 somerset ct, nashville, tn 37217, united s...      1

[9037 rows x 2 columns]

In [77]:
test.loc[test['count'] == 1]

                                       Incident Address  count
2100  1902 pinehurst dr, nashville, tn 37216, united...      1
2101                                   610 tobylynn cir      1
2102  508 annex ave, nashville, tn 37209, united states      1
2103   454 capri dr, nashville, tn 37209, united states      1
2104  6342 torrington rd, nashville, tn 37205, unite...      1
...                                                 ...    ...
9032  181 thompson ln, nashville, tn 37211, united s...      1
9033                                  1604 ardenwood ct      1
9034  255 haverford ave, nashville, tn 37205, united...      1
9035                                  6604 fleetwood dr      1
9036  604 somerset ct, nashville, tn 37217, united s...      1

[6937 rows x 2 columns]

In [79]:
test['Incident Address'].nunique()

9037

In [69]:
trash_hauler['Incident Address'].nunique()

9037

In [57]:
trash_hauler = trash_hauler.dropna(subset=['Incident Address'])

In [59]:
trash_hauler['Incident Address'] = trash_hauler['Incident Address'].astype(str).str.lower()

C:\Users\user\AppData\Local\Temp\ipykernel_17100\2816936794.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trash_hauler['Incident Address'] = trash_hauler['Incident Address'].astype(str).str.lower()

In [61]:
trash_hauler['Incident Address'].nunique()

9037

In [ ]:
address_counts = trash_hauler['Incident Address'].value_counts()
address_counts

In [ ]:
frequent_addresses = address_counts[address_counts >= 2]
frequent_addresses

In [ ]:
.index brings back only unique addresses that meet the condition of appearing at least twice. 
address_counts pulls the actual addresses, not the count after filtering.

In [ ]:
trash_hauler = trash_hauler[trash_hauler['Incident Address'].isin(frequent_addresses)]

Filters trash_hauler DF to only include the rows where incident address is one of the frequent addresses (those that appeared 2 or more times).

In [ ]:
print(trash_hauler)

trash_hauler = hauler.loc[
    (hauler['Description'].str.contains('miss') == True) |
    (hauler['Complaint'].str.contains('Missed') == True)]
trash_hauler

repeated_addresses.loc[:, 'Incident Address'] = repeated_addresses['Incident Address'].str.split(',').str[0]
repeated_addresses

repeated_addresses = repeated_addresses['Incident Address'].astype(str).str.upper()
repeated_addresses

repeated_addresses = repeated_addresses.nunique()
repeated_addresses.shape[0]

repeated_addresses