In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re

In [2]:
trash = pd.read_csv('../data/trash_hauler_report.csv')

In [3]:
trash.head(40)

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1.727970e+06,686779.478089
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066
5,25317,11/01/17,Trash Collection Complaint,left trash cart in middle of driveway instead ...,3602 floral dr,37211.0,RED RIVER,4304,16.0,1.751660e+06,643215.201073
6,25325,11/01/17,Damage to Property,Trash/emptied Wednesday & now metal black-mail...,4721 Chalmers Dr,37215.0,RED RIVER,3303,34.0,1.726301e+06,637078.402245
7,25327,11/01/17,Trash Collection Complaint,"Trash out on time, miss again Tuesday. ALLEY",1816 Jo Johnston Ave,37203.0,METRO,9208,21.0,1.731459e+06,666013.601229
8,25330,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1.794534e+06,618749.342732
9,25331,11/01/17,Trash - Curbside/Alley Missed Pickup,"Trash missed Tuesday again, ALLEY",1206 Ireland St,37208.0,METRO,9208,19.0,1.733029e+06,668762.640891
10,25341,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed trash pickup - resident has at curb for...,3113 HYDES FERRY RD,37218.0,RED RIVER,4204,2.0,1.721578e+06,676018.399900
11,25350,11/01/17,Trash Collection Complaint,Missed- 4th week in a row.,3210 Whites Creek Pike,37207.0,RED RIVER,3201,3.0,1.726433e+06,691919.200296
12,25359,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed. Does not have access to alley.,830 Meridian St,37207.0,METRO,9207,5.0,1.741745e+06,675328.666057
13,25366,11/01/17,Trash Collection Complaint,trash truck took cart \r\n3 guys on truck did ...,2200 osage st,37208.0,METRO,9201,21.0,1.728645e+06,672074.099110
14,25370,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,6543 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.706942e+06,659614.183556
15,25371,11/01/17,Trash - Curbside/Alley Missed Pickup,Pickup missed,2218 BUENA VISTA PIKE,37218.0,RED RIVER,4204,2.0,1.724506e+06,679777.599716
16,25393,11/01/17,Trash Collection Complaint,trash carts all tossed in road after pick up,2720 riverbend dr,37214.0,RED RIVER,1501,15.0,1.762456e+06,693225.665703
17,25407,11/01/17,Trash Collection Complaint,Curb/Trash miss everyone already gotten pick u...,4209 Lone Oak Rd,37215.0,RED RIVER,3305,25.0,1.729355e+06,644389.920699
18,25449,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss for this address and others. T...,356 Kingview Dr,37218.0,RED RIVER,3204,1.0,1.722026e+06,685779.071233
19,25454,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,449 Westboro Dr,37209.0,RED RIVER,4201,20.0,1.710615e+06,661992.330671
20,25465,11/01/17,Trash Collection Complaint,A resident is complaining that a trash truck r...,1414 Old Hickory Blvd,37207.0,NaN,NaN,3.0,1.738737e+06,711231.799782
21,25469,11/01/17,Trash - Curbside/Alley Missed Pickup,"Our trash was not picked up today, Wed, Nov 1....",117 Lafayette Ct,37205.0,RED RIVER,1302,23.0,1.713465e+06,644882.402008
22,25471,11/01/17,Trash - Curbside/Alley Missed Pickup,"Alley trash miss Tuesday, also others as well,...",1904 MeHarry Blvd,37208.0,METRO,9208,21.0,1.730048e+06,668927.190485
23,25474,11/01/17,Trash - Curbside/Alley Missed Pickup,Customer says backdoor pickup was missed the p...,1144 Sewanee Rd,37220.0,RED RIVER,3302,34.0,1.731663e+06,639182.402269
24,25496,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed pickup,1815 WOODMONT BLVD,37215.0,RED RIVER,3305,25.0,1.730532e+06,648861.631860
25,25506,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,405 Page Rd,37205.0,RED RIVER,1302,34.0,1.711547e+06,639925.602166
26,25507,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed pickup,4722 DANBY DR,37211.0,RED RIVER,4302,26.0,1.748483e+06,636882.402278
27,25508,11/01/17,Trash Collection Complaint,missed. Neighbor missed as well-say she is at ...,2812 27TH AVE S,37212.0,RED RIVER,2305,18.0,1.729022e+06,652985.679115
28,25509,11/01/17,Trash - Curbside/Alley Missed Pickup,cust says entire street was missed,4506 DAKOTA AVE,37209.0,RED RIVER,1308,24.0,1.720100e+06,661552.800934
29,25511,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,259 Sunrise Ave,37211.0,RED RIVER,4304,16.0,1.750610e+06,645187.680933
30,25512,11/01/17,Trash - Curbside/Alley Missed Pickup,cust says entire street was missed,4311 dakota ave,37209.0,RED RIVER,1308,24.0,1.720100e+06,661552.800934
31,25515,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed. Cart is still out,4029 Graybar Ct,37215.0,RED RIVER,3305,25.0,1.729986e+06,648821.425466
32,25517,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed.,524 Harding Pl,37211.0,RED RIVER,4302,26.0,1.751209e+06,635651.200956
33,25519,11/01/17,Trash Collection Complaint,"5th time in as many weeks, Metro has not picke...",3702 Hobbs Rd,37215.0,RED RIVER,3304,34.0,1.721317e+06,645218.701908
34,25522,11/01/17,Trash - Curbside/Alley Missed Pickup,Second week in a row for no trash pickup.,405 brook hollow rd,37205.0,RED RIVER,1301,23.0,1.706843e+06,646820.002288
35,25525,11/01/17,Trash Collection Complaint,Missed my trash AGAIN.\r\ncheck your records. ...,162 antioch pike,37211.0,RED RIVER,4304,16.0,1.753145e+06,644275.202194
36,25529,11/01/17,Trash - Curbside/Alley Missed Pickup,The trash can was missed this week. They picke...,131 page rd,37205.0,RED RIVER,1302,34.0,1.712020e+06,642604.860911
37,25535,11/02/17,Trash Collection Complaint,Missed- several weeks in a row.,3704 Hobbs Rd,37215.0,RED RIVER,3304,34.0,1.721321e+06,645165.752310
38,25536,11/02/17,Trash - Curbside/Alley Missed Pickup,trash missed Wednesday. Curb,6011 Jocelyn Hollow Rd,37205.0,RED RIVER,1304,23.0,1.711334e+06,649685.901492
39,25539,11/02/17,Trash - Curbside/Alley Missed Pickup,Alley trash miss for Wednesday. Wants cart emp...,2524 Batavia St,37208.0,METRO,9303,21.0,1.727574e+06,666486.401815

In [4]:
trash['Request ']

0                            Trash - Backdoor
1        Trash - Curbside/Alley Missed Pickup
2        Trash - Curbside/Alley Missed Pickup
3        Trash - Curbside/Alley Missed Pickup
4        Trash - Curbside/Alley Missed Pickup
                         ...
20221    Trash - Curbside/Alley Missed Pickup
20222    Trash - Curbside/Alley Missed Pickup
20223    Trash - Curbside/Alley Missed Pickup
20224    Trash - Curbside/Alley Missed Pickup
20225    Trash - Curbside/Alley Missed Pickup
Name: Request , Length: 20226, dtype: object

In [5]:
# trashn = trash.loc[trash["Request "].isnull() == False]
trash['Request '].isnull().sum()
trash['Description'].isnull().sum()

31

In [6]:
trash['Request '] = trash['Request '].astype('string')
trash['Description'] = trash['Description'].astype('string')
trash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  object
 2   Request           20226 non-null  string
 3   Description       20195 non-null  string
 4   Incident Address  20217 non-null  object
 5   Zip Code          20151 non-null  float64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       19279 non-null  object
 8   Council District  20177 non-null  float64
 9   State Plan X      20198 non-null  float64
 10  State Plan Y      20198 non-null  float64
dtypes: float64(4), int64(1), object(4), string(2)
memory usage: 1.7+ MB

In [7]:
trash['Description'] = trash['Description'].fillna("").str.lower().astype('string')
# for Description in trash:
#     if re.findall(r"miss\w?", Description):
#         trash = trash['Description']

# trash.head(40)

In [8]:
# trashp = trash.loc[trash['Description'].str.contains('miss') == True]
# trashp

In [9]:
# trashm = trash.loc[trash['Request '].str.contains("Missed") == True]
trashm = trash.loc[
    (trash['Description'].str.contains('miss') == True) |
    (trash['Request '].str.contains('Missed') == True)]
trashm

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,curb/trash miss tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,curb/trash miss tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066
7,25327,11/01/17,Trash Collection Complaint,"trash out on time, miss again tuesday. alley",1816 Jo Johnston Ave,37203.0,METRO,9208,21.0,1.731459e+06,666013.601229
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,missed...neighbors missed,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1.781137e+06,632448.551144
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1.749711e+06,669201.601569
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1.781360e+06,637742.006846

In [10]:
trashl = trashm.loc[trashm['Trash Hauler'].str.contains("RED RIVER") == True]
trashl

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,curb/trash miss tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,curb/trash miss tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066
8,25330,11/01/17,Trash - Curbside/Alley Missed Pickup,missed.,4484 Lavergne Couchville Pike,37013.0,RED RIVER,4210,33.0,1.794534e+06,618749.342732
10,25341,11/01/17,Trash - Curbside/Alley Missed Pickup,missed trash pickup - resident has at curb for...,3113 HYDES FERRY RD,37218.0,RED RIVER,4204,2.0,1.721578e+06,676018.399900
...,...,...,...,...,...,...,...,...,...,...,...
20220,267121,11/01/19,Trash - Curbside/Alley Missed Pickup,missed,"2709 Crestdale Dr, Nashville, TN 37214, United...",37214.0,RED RIVER,1502,15.0,1.770240e+06,676334.399319
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,missed...neighbors missed,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1.781137e+06,632448.551144
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1.781360e+06,637742.006846

In [11]:
trashl['Incident Address'].nunique()

9227

In [12]:
trashl.value_counts('Incident Address')

Incident Address
12546 Old Hickory Blvd, Nashville, TN 37013, United States    19
5135 Hickory Hollow Pkwy                                      18
6007 Obrien Ave, Nashville, TN 37209, United States           18
802 Crescent Rd, Nashville, TN 37205, United States           17
3710 N NATCHEZ CT                                             17
                                                              ..
2909 Jones Ave, Nashville, TN 37207, United States             1
2909 Elm Hill Pike, Nashville, TN 37214, United States         1
2908 Tyne Blvd, Nashville, TN 37215, United States             1
2908 Mashburn Rd, Nashville, TN 37211, United States           1
fransworth dr                                                  1
Name: count, Length: 9227, dtype: int64

In [14]:
trash.loc[:, 'Incident Address'] = trashl['Incident Address'].astype('string')
trashl.loc[:, 'Incident Address'] = trashl['Incident Address'].str.lower().str.title()
# trashl.loc[trashl['Incident Address'].str.contains('607 Estes Rd')]

In [15]:
trashl.loc[:, 'Incident Address'] = trashl['Incident Address'].str.replace("United States", "")
trashl.loc[:, 'Incident Address'] = trashl['Incident Address'].str.replace("Tennessee", "Tn")
trashl.loc[:, 'Incident Address'] = trashl['Incident Address'].str.replace("Tn", "")
# trashl['Incident Address'] = trashl['Incident Address'].str.replace(",", "")
trashl['Incident Address'].nunique()

9052

In [16]:
trashl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12841 entries, 1 to 20225
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    12841 non-null  int64
 1   Date Opened       12841 non-null  object
 2   Request           12841 non-null  string
 3   Description       12841 non-null  string
 4   Incident Address  12840 non-null  object
 5   Zip Code          12813 non-null  float64
 6   Trash Hauler      12841 non-null  object
 7   Trash Route       12839 non-null  object
 8   Council District  12828 non-null  float64
 9   State Plan X      12836 non-null  float64
 10  State Plan Y      12836 non-null  float64
dtypes: float64(4), int64(1), object(4), string(2)
memory usage: 1.7+ MB

In [25]:
trashl.loc[:, 'Incident Address'] = trashl['Incident Address'].str.rsplit(',').str[0]

trashl['Incident Address'].nunique()
# trashl['Incident Address'].re.search(r',\sTn\d{5},?')

8243

In [18]:
un = print(trashl['Incident Address'].unique())

['4028 Clarksville Pike' '6528 Thunderbird Dr' '604 Croley Dr' ...
 '3945 Stewarts Ln' '2709 Crestdale Dr' '604 Somerset Ct']

In [19]:
nonun = trashl.shape
nonun1 = str(nonun)

In [20]:
type(nonun1)
print(nonun1)

(12841, 11)

In [21]:
nonun2 = print(nonun1[1:5])

1284

In [22]:
nonun3 = str(nonun2)
un2 = str(un)
type(nonun3)
type(un2)

str

In [24]:
(12841 - 8244) * 200

919400